# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh"
source "/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/tmux/tmux.plugin.zsh"
source "/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/vi-mode/vi-mode.plugin.zsh"
source "/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/z/z.plugin.zsh"
source "/Users/dmitri/.zgen/Tarrasch/zsh-bd-master/bd.plugin.zsh"
source "/Users/dmitri/.zgen/lukechilds/zsh-better-npm-completion-master/zsh-better-npm-completion.plugin.zsh"
source "/Users/dmitri/.zgen/hlissner/zsh-autopair-master/autopair.plugin.zsh"
source "/Users/dmitri/.zgen/hlissner/zsh-autopair-master/zsh-autopair.plugin.zsh"
source "/Users/dmitri/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/Users/dmitri/.zgen/denysdovhan/spaceship-prompt-master/spaceship.zsh-theme"

# ### Plugins & Completions
fpath=(/Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master /Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/git /Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/tmux /Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/vi-mode /Users/dmitri/.zgen/robbyrussell/oh-my-zsh-master/plugins/z /Users/dmitri/.zgen/Tarrasch/zsh-bd-master /Users/dmitri/.zgen/lukechilds/zsh-better-npm-completion-master /Users/dmitri/.zgen/hlissner/zsh-autopair-master /Users/dmitri/.zgen/zsh-users/zsh-completions-master/src /Users/dmitri/.zgen/zsh-users/zsh-syntax-highlighting-master /Users/dmitri/.zgen/denysdovhan/spaceship-prompt-master ${fpath})

autoload -Uz compinit && \
   compinit -C 

# }}}
